# Generated by Django 3.2.6 on 2022-01-08 13:22

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carmanagment', '0037_auto_20220108_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddDepositCarRentPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Сумма')),
            ],
            options={
                'verbose_name': 'Добавить депозитные средства',
                'verbose_name_plural': 'Добавить депозитные средства',
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CarInRentPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=datetime.datetime(2022, 1, 8, 13, 22, 25, 861342, tzinfo=utc), verbose_name='Дата и время начала аренды')),
                ('end_time', models.DateTimeField(default=datetime.datetime(2022, 1, 11, 13, 22, 25, 861342, tzinfo=utc), verbose_name='Дата и время завершения аренды')),
                ('amount', models.FloatField(validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Сумма')),
                ('deposit', models.FloatField(validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Залог')),
            ],
            options={
                'verbose_name': 'Сдача машины в аренду',
                'verbose_name_plural': 'Сдача машины в аренду',
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PenaltyDepositCarRentPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Сумма')),
            ],
            options={
                'verbose_name': 'Штраф на арендованую машину',
                'verbose_name_plural': 'Штраф на арендованую машину',
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReturnCarRentAdmin_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Возврат машины',
                'verbose_name_plural': 'Возврат машины',
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReturnCarRentPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Срочный возврат машины из аренды',
                'verbose_name_plural': 'Срочный возврат машины из аренды',
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RentPageModelAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CarSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('end_rent', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Аренда завершена')),
                ('deposit', models.FloatField(default=0.0, verbose_name='Залог')),
                ('paid_deposit', models.FloatField(default=0.0, verbose_name='Оплаченый залог')),
                ('amount', models.FloatField(default=0.0, verbose_name='Оплаченый залог')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carmanagment.car', verbose_name='Машина')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carmanagment.driver', verbose_name='Арендатор')),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_price', to='carmanagment.rentprice', verbose_name='тариф')),
            ],
            options={
                'verbose_name': 'Аренда авто',
                'verbose_name_plural': 'Расписание аренды авто',
            },
        ),
        migrations.CreateModel(
            name='ReturnRentPageModelAdmin',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('carrent.carschedule',),
        ),
    ]
