# Generated by Django 3.2.6 on 2022-01-31 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='имя/название/гос номер')),
                ('currency', models.PositiveSmallIntegerField(choices=[(0, 'грн'), (1, '$')], default=0, verbose_name='валюта')),
            ],
            options={
                'verbose_name': 'Баланс',
                'verbose_name_plural': 'Балансы',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactionTime', models.DateTimeField(auto_now_add=True, verbose_name='Время транзакции')),
                ('transactionType', models.IntegerField(choices=[(0, 'Расход'), (1, 'Приход'), (3, 'Перевод средств между счетами'), (4, 'Внесение денежных средств '), (5, 'Вывод денежных средств'), (6, 'Инвестиция'), (7, 'Строховка')], verbose_name='Тип')),
                ('comment', models.TextField(blank=True, default='', max_length=1000, null=True)),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'транзакции',
            },
        ),
        migrations.CreateModel(
            name='CashBox',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='balance.account')),
            ],
            options={
                'verbose_name': 'Касса',
                'verbose_name_plural': 'Кассы',
            },
            bases=('balance.account',),
        ),
        migrations.CreateModel(
            name='AccountTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField()),
                ('comment', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='balance.account')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='balance.transaction')),
            ],
            options={
                'verbose_name': 'Операция в транзакция',
                'verbose_name_plural': 'Транзакционные операции',
            },
        ),
        migrations.CreateModel(
            name='AccountStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statementDate', models.DateField()),
                ('closingBalance', models.BigIntegerField()),
                ('totalCredit', models.BigIntegerField()),
                ('totalDebit', models.BigIntegerField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='balance.account')),
            ],
            options={
                'verbose_name': 'Состояния баланса за дату',
                'verbose_name_plural': 'Переодические состояния балансов',
                'ordering': ('account', 'statementDate'),
                'unique_together': {('account', 'statementDate')},
            },
        ),
        migrations.AddField(
            model_name='account',
            name='last_period_balance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='for_account', to='balance.accountstatement', verbose_name='Последний зафиксированный баланс'),
        ),
    ]
