# Generated by Django 3.2.6 on 2021-09-01 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ('name',), 'verbose_name': 'Баланс', 'verbose_name_plural': 'Балансы'},
        ),
        migrations.AlterModelOptions(
            name='accountstatement',
            options={'ordering': ('account', 'statementDate'), 'verbose_name': 'Состояния баланса за дату', 'verbose_name_plural': 'Переодические состояния балансов'},
        ),
        migrations.AlterModelOptions(
            name='accounttransaction',
            options={'verbose_name': 'Операция в транзакция', 'verbose_name_plural': 'Транзакционные операции'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': 'Транзакция', 'verbose_name_plural': 'транзакции'},
        ),
        migrations.AddField(
            model_name='account',
            name='currency',
            field=models.PositiveSmallIntegerField(choices=[(0, 'грн'), (1, '$')], default=0, verbose_name='валюта'),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_period_balance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='for_account', to='balance.accountstatement', verbose_name='Последний зафиксированный баланс'),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=250, verbose_name='имя/название/гос номер'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transactionTime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время транзакции'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transactionType',
            field=models.IntegerField(choices=[(0, 'Расход'), (1, 'Приход'), (3, 'Перевод средств между счетами'), (4, 'Внесение денежных средств '), (5, 'Вывод денежных средств')], verbose_name='Тип'),
        ),
        migrations.AlterUniqueTogether(
            name='accountstatement',
            unique_together={('account', 'statementDate')},
        ),
    ]
