# Generated by Django 3.2.6 on 2021-08-26 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountstatement',
            name='statementDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transactionTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
