# Generated by Django 3.2.6 on 2021-09-01 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0002_auto_20210901_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transactionType',
            field=models.IntegerField(choices=[(0, 'Расход'), (1, 'Приход'), (3, 'Перевод средств между счетами'), (4, 'Внесение денежных средств '), (5, 'Вывод денежных средств'), (6, 'Инвестиция')], verbose_name='Тип'),
        ),
    ]
