# Generated by Django 3.2.6 on 2021-11-19 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0004_auto_20210920_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transactionType',
            field=models.IntegerField(choices=[(0, 'Расход'), (1, 'Приход'), (3, 'Перевод средств между счетами'), (4, 'Внесение денежных средств '), (5, 'Вывод денежных средств'), (6, 'Инвестиция'), (7, 'Строховка')], verbose_name='Тип'),
        ),
    ]
