# Generated by Django 3.2.6 on 2021-12-02 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0005_alter_transaction_transactiontype'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashBox',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='balance.account')),
            ],
            options={
                'verbose_name': 'Касса',
                'verbose_name_plural': 'Кассы',
            },
            bases=('balance.account',),
        ),
    ]
