# Generated by Django 3.2.6 on 2022-01-30 17:07

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('car_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarSummaryStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_date', models.DateField(default=datetime.datetime(2022, 1, 30, 17, 7, 38, 753336, tzinfo=utc), verbose_name='Дата')),
                ('stat_interval', models.PositiveIntegerField(default=86400, verbose_name='Интервал')),
                ('gps_mileage', models.FloatField(default=0, verbose_name='Пробег по трекеру')),
                ('taxi_mileage', models.FloatField(default=0, verbose_name='Пробег по оператору такси')),
                ('taxi_trip_count', models.PositiveIntegerField(default=0, verbose_name='Кол-во поездок в такси')),
                ('branding_amount', models.FloatField(default=0, verbose_name='Доход за брендирование')),
                ('taxi_amount', models.FloatField(default=0, verbose_name='Доход от таксопарка')),
                ('rent_amount', models.FloatField(default=0, verbose_name='Доход от аренды')),
                ('expense', models.FloatField(default=0, verbose_name='Расходы')),
                ('capital_expense', models.FloatField(default=0, verbose_name='Капитальные расходы')),
                ('operate', models.FloatField(default=0, verbose_name='Операционные затраты')),
                ('investor_amount', models.FloatField(default=0, verbose_name='Прибыль инвестора')),
                ('driver_amount', models.FloatField(default=0, verbose_name='Зарплата водителя')),
                ('report_paid', models.DateField(blank=True, null=True, verbose_name='Дата оплаты по отчету')),
                ('plan_for_paid', models.BooleanField(default=False, verbose_name='Отчет требует оплаты')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='car_management.car')),
            ],
            options={
                'verbose_name': 'Статистика по Авто',
                'verbose_name_plural': 'Статистика по Авто',
                'unique_together': {('car', 'stat_date', 'stat_interval')},
            },
        ),
    ]
