# Generated by Django 3.2.6 on 2022-01-30 18:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trip_stat', '0002_alter_carsummarystatistics_stat_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carsummarystatistics',
            name='stat_date',
            field=models.DateField(default=datetime.datetime(2022, 1, 30, 18, 0, 46, 219119, tzinfo=utc), verbose_name='Дата'),
        ),
    ]
