# Generated by Django 3.2.6 on 2022-01-30 17:07

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('balance', '0006_cashbox'),
        ('car_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxiOperator',
            fields=[
                ('counterpart_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='car_management.counterpart')),
                ('cash_profit', models.FloatField(default=17, verbose_name='Коэффициент прибили с поезди оператора (нал)')),
                ('profit', models.FloatField(default=17, verbose_name='Коэффициент прибили с поезди оператора (без нал)')),
                ('bank_interest', models.FloatField(default=2.5, verbose_name='Комиссия за перевод (без нал)')),
                ('cash_box', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='balance.cashbox')),
            ],
            options={
                'verbose_name': 'Оператор такси',
                'verbose_name_plural': 'Оператор такси',
            },
            bases=('car_management.counterpart',),
        ),
        migrations.CreateModel(
            name='CarsInOperator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal', models.CharField(default='', max_length=7, verbose_name='Позывной')),
                ('car_uid', models.CharField(blank=True, max_length=255, null=True, verbose_name='Идентификатор машины')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cars_in_taxi', to='car_management.car', verbose_name='Машина')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxi_park', to='car_rent.taxioperator', verbose_name='Таксопарк')),
            ],
            options={
                'verbose_name': 'Машины в таксопарках',
                'verbose_name_plural': 'Машины в таксопарках',
                'unique_together': {('operator', 'signal'), ('operator', 'car_uid')},
            },
        ),
        migrations.CreateModel(
            name='BrandingAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_date', models.DateField(default=datetime.datetime(2022, 1, 30, 17, 7, 38, 791276, tzinfo=utc), verbose_name='Дата')),
                ('amount', models.FloatField(default=0, verbose_name='Доход от брендирования')),
                ('operate', models.FloatField(default=14, verbose_name='Операционные затраты')),
                ('investor_amount', models.FloatField(default=14, verbose_name='Прибыль инвестора')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_management.car')),
            ],
            options={
                'verbose_name': 'Брендирование',
                'verbose_name_plural': 'Брендирование',
                'unique_together': {('car', 'stat_date')},
            },
        ),
    ]
