# Generated by Django 3.2.6 on 2022-01-30 17:44

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('car_management', '0002_alter_carmileage_stat_date'),
        ('car_rent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddDepositCarRentPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Сумма')),
            ],
            options={
                'verbose_name': 'Добавить депозитные средства',
                'verbose_name_plural': 'Добавить депозитные средства',
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CarInRentPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=datetime.datetime(2022, 1, 30, 17, 44, 0, 486862, tzinfo=utc), verbose_name='Дата и время начала аренды')),
                ('end_time', models.DateTimeField(default=datetime.datetime(2022, 2, 2, 17, 44, 0, 486862, tzinfo=utc), verbose_name='Дата и время завершения аренды')),
                ('amount', models.FloatField(validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Сумма')),
                ('deposit', models.FloatField(validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Залог')),
            ],
            options={
                'verbose_name': 'Сдача машины в аренду',
                'verbose_name_plural': 'Сдача машины в аренду',
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PenaltyDepositCarRentPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Сумма')),
            ],
            options={
                'verbose_name': 'Штраф на арендованую машину',
                'verbose_name_plural': 'Штраф на арендованую машину',
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReturnCarRentPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Срочный возврат машины из аренды',
                'verbose_name_plural': 'Срочный возврат машины из аренды',
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RentPageModelAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='brandingamount',
            name='stat_date',
            field=models.DateField(default=datetime.datetime(2022, 1, 30, 17, 44, 0, 495829, tzinfo=utc), verbose_name='Дата'),
        ),
        migrations.CreateModel(
            name='CarSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('end_rent', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Аренда завершена')),
                ('paid_deposit', models.FloatField(default=0.0, verbose_name='Оплаченный залог')),
                ('amount', models.FloatField(default=0.0, verbose_name='Оплаченная сумма за аренду')),
                ('work_in_taxi', models.BooleanField(default=False, verbose_name='Работает в нашем такси')),
                ('auto_renew', models.BooleanField(default=False, verbose_name='Автоматически обновлять план аренды')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_management.car', verbose_name='Машина')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='car_management.driver', verbose_name='Арендатор')),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_price', to='car_management.rentprice', verbose_name='тариф')),
                ('taxi_operators', models.ManyToManyField(to='car_rent.CarsInOperator', verbose_name='операторы такси')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_terms', to='car_management.rentterms', verbose_name='условия')),
            ],
            options={
                'verbose_name': 'Аренда авто',
                'verbose_name_plural': 'Расписание аренды авто',
            },
        ),
        migrations.CreateModel(
            name='ReturnRentPageModelAdmin',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('car_rent.carschedule',),
        ),
    ]
