# Generated by Django 3.2.6 on 2022-01-30 18:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('car_rent', '0002_auto_20220130_1944'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnCarRentAdmin_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Возврат машины',
                'verbose_name_plural': 'Возврат машины',
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='brandingamount',
            name='stat_date',
            field=models.DateField(default=datetime.datetime(2022, 1, 30, 18, 0, 46, 260977, tzinfo=utc), verbose_name='Дата'),
        ),
    ]
