# Generated by Django 3.2.6 on 2022-02-02 17:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('car_rent', '0002_auto_20220131_2300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carschedule',
            name='price',
        ),
        migrations.AddField(
            model_name='carschedule',
            name='min_time',
            field=models.PositiveIntegerField(default=0, verbose_name='Минимальный срок аренды'),
        ),
        migrations.AlterField(
            model_name='brandingamount',
            name='stat_date',
            field=models.DateField(default=datetime.datetime(2022, 2, 2, 17, 56, 2, 40197, tzinfo=utc), verbose_name='Дата'),
        ),
    ]
