# Generated by Django 3.2.6 on 2022-02-08 19:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('car_rent', '0004_auto_20220206_0017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carschedule',
            name='trip_many_paid',
        ),
        migrations.AddField(
            model_name='carschedule',
            name='paid_type',
            field=models.PositiveIntegerField(choices=[(0, 'Не заводить транзакции по поездкам'), (1, 'Детальное расписание операций'), (3, 'Только корректировки баланса')], default=0, verbose_name='Тип проводимых платежей'),
        ),
        migrations.AddField(
            model_name='carschedule',
            name='statistics_type',
            field=models.PositiveIntegerField(choices=[(0, 'Не вести статистику, машина отключена'), (1, 'Только статистика по поездкам'), (2, 'Только статистика по дням'), (10, 'Статистика по поездкам и оплата по дням'), (20, 'Оплата по поездкам и статистика по дням')], default=10, verbose_name='Тип собираемой статистики'),
        ),
        migrations.AlterField(
            model_name='brandingamount',
            name='stat_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата'),
        ),
    ]
