# Generated by Django 3.2.6 on 2022-01-31 21:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('car_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmileage',
            name='stat_date',
            field=models.DateField(default=datetime.datetime(2022, 1, 31, 21, 0, 25, 386504, tzinfo=utc), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=15, null=True, verbose_name='Телефон'),
        ),
    ]
