# Generated by Django 3.2.6 on 2022-02-02 17:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('car_management', '0002_auto_20220131_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentprice',
            name='work_in_taxi',
            field=models.BooleanField(default=False, verbose_name='Работа в такси'),
        ),
        migrations.AlterField(
            model_name='carmileage',
            name='stat_date',
            field=models.DateField(default=datetime.datetime(2022, 2, 2, 17, 56, 2, 25198, tzinfo=utc), verbose_name='Дата'),
        ),
    ]
