# Generated by Django 3.2.6 on 2022-01-30 18:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('car_management', '0002_alter_carmileage_stat_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='profit',
        ),
        migrations.AddField(
            model_name='rentterms',
            name='profit',
            field=models.FloatField(default=50, verbose_name='Процент распределения прибыли'),
        ),
        migrations.AlterField(
            model_name='carmileage',
            name='stat_date',
            field=models.DateField(default=datetime.datetime(2022, 1, 30, 18, 0, 46, 211145, tzinfo=utc), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='rentterms',
            name='amount_control',
            field=models.BooleanField(default=False, verbose_name='Контроль за суммой кассы'),
        ),
        migrations.AlterField(
            model_name='rentterms',
            name='control_interval_paid_distance',
            field=models.PositiveIntegerField(default=1, verbose_name='Оплата за интервал'),
        ),
        migrations.AlterField(
            model_name='rentterms',
            name='max_millage',
            field=models.PositiveIntegerField(default=2000, verbose_name='Макс км за интервал'),
        ),
        migrations.AlterField(
            model_name='rentterms',
            name='millage_control',
            field=models.BooleanField(default=True, verbose_name='Контроль за километражем'),
        ),
        migrations.AlterField(
            model_name='rentterms',
            name='plan_amount',
            field=models.FloatField(default=2500, verbose_name='План по кассе'),
        ),
        migrations.AlterField(
            model_name='rentterms',
            name='trips_control',
            field=models.BooleanField(default=True, verbose_name='Контроль за количеством поездок'),
        ),
    ]
