# Generated by Django 3.2.6 on 2022-02-05 22:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('car_management', '0003_auto_20220202_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmileage',
            name='stat_date',
            field=models.DateField(default=datetime.datetime(2022, 2, 5, 22, 17, 46, 680803, tzinfo=utc), verbose_name='Дата'),
        ),
    ]
