# Generated by Django 3.2.6 on 2022-02-08 19:08

import audit_log.models.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('car_management', '0004_alter_carmileage_stat_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Профиль пользователя', 'verbose_name_plural': 'Профили пользователя'},
        ),
        migrations.AddField(
            model_name='expenses',
            name='is_template',
            field=models.BooleanField(default=True, verbose_name='Черновик'),
        ),
        migrations.AddField(
            model_name='expenses',
            name='paid_by',
            field=audit_log.models.fields.LastUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expenses',
            name='paid_date_mark',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='investor',
            name='limit_to_investor_confirm',
            field=models.FloatField(default=-1, verbose_name='Сумма от которой требуется подверждение менеджера'),
        ),
        migrations.AddField(
            model_name='investor',
            name='limit_to_manager_confirm',
            field=models.FloatField(default=10000, verbose_name='Сумма от которой требуется подверждение менеджера'),
        ),
        migrations.AddField(
            model_name='rentprice',
            name='paid_type',
            field=models.PositiveIntegerField(choices=[(0, 'Не заводить транзакции по поездкам'), (1, 'Детальное расписание операций'), (3, 'Только корректировки баланса')], default=0, verbose_name='Тип проводимых платежей'),
        ),
        migrations.AddField(
            model_name='rentprice',
            name='statistics_type',
            field=models.PositiveIntegerField(choices=[(0, 'Не вести статистику, машина отключена'), (1, 'Только статистика по поездкам'), (2, 'Только статистика по дням'), (10, 'Статистика по поездкам и оплата по дням'), (20, 'Оплата по поездкам и статистика по дням')], default=10, verbose_name='Тип собираемой статистики'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_confirm_as_investor',
            field=models.BooleanField(default=False, verbose_name='Может подтверждать как инвестор'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_confirm_as_manager',
            field=models.BooleanField(default=False, verbose_name='Может подтверждать как менеджер'),
        ),
        migrations.AlterField(
            model_name='carmileage',
            name='stat_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата'),
        ),
    ]
