# Generated by Django 3.2.6 on 2021-08-26 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('balance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assistant',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='balance.account')),
            ],
            bases=('balance.account',),
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='balance.account')),
                ('date_start', models.DateField(auto_created=True, auto_now_add=True)),
                ('year', models.PositiveSmallIntegerField()),
                ('mileage_at_start', models.PositiveIntegerField(verbose_name='')),
                ('control_mileage', models.PositiveIntegerField(verbose_name='')),
                ('last_TO_date', models.DateField(null=True)),
                ('wialon_id', models.CharField(max_length=50, verbose_name='ID в системе WIALON')),
            ],
            bases=('balance.account',),
        ),
        migrations.CreateModel(
            name='CarBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Бренд')),
            ],
        ),
        migrations.CreateModel(
            name='Counterpart',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='balance.account')),
            ],
            bases=('balance.account',),
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='balance.account')),
            ],
            bases=('balance.account',),
        ),
        migrations.CreateModel(
            name='ExpensesTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentCarBalance',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='balance.account')),
                ('create_date', models.DateField(auto_created=True)),
            ],
            bases=('balance.account',),
        ),
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='balance.account')),
                ('profit', models.FloatField()),
            ],
            bases=('balance.account',),
        ),
        migrations.CreateModel(
            name='WialonTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='Дата начала поездки')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения поездки')),
                ('mileage', models.PositiveIntegerField(verbose_name='Пробег по трекеру')),
                ('fuel', models.PositiveIntegerField(verbose_name='Раход по трекеру')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carmanagment.car')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carmanagment.driver', verbose_name='Водитель, если известно')),
            ],
        ),
        migrations.CreateModel(
            name='TaxiTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='Дата начала поездки')),
                ('mileage', models.PositiveIntegerField(verbose_name='Пробег по трекеру')),
                ('fuel', models.PositiveIntegerField(verbose_name='Раход по пробегу')),
                ('amount', models.PositiveBigIntegerField(verbose_name='Сумма оплаты')),
                ('cash', models.BooleanField(verbose_name='Оплата наличными')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carmanagment.car')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carmanagment.driver', verbose_name='Водитель, если известно')),
                ('payer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='balance.account', verbose_name='Плательщик/От кого приняли средства')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='balance.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_mark', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('amount', models.PositiveBigIntegerField()),
                ('description', models.TextField()),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carmanagment.car')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carmanagment.driver')),
                ('expenseType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carmanagment.expensestypes')),
                ('investor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carmanagment.investor')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='balance.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Модель')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carmanagment.carbrand')),
            ],
        ),
        migrations.CreateModel(
            name='CarMileage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mileage_at_start', models.PositiveIntegerField(verbose_name='')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mileage', to='carmanagment.car')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='car_investor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='carmanagment.investor'),
        ),
        migrations.AddField(
            model_name='car',
            name='investment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='car', to='carmanagment.investmentcarbalance'),
        ),
        migrations.AddField(
            model_name='car',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carmanagment.carmodel'),
        ),
    ]
