# Generated by Django 3.2.6 on 2021-08-27 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carmanagment', '0002_alter_expenses_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='wialon_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID в системе WIALON'),
        ),
    ]
