# Generated by Django 3.2.6 on 2021-09-01 13:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carmanagment', '0003_alter_car_wialon_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='mileage_at_start',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Пробег при поступлении'),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(2100), django.core.validators.MinValueValidator(1900)], verbose_name='Год выпуска'),
        ),
    ]
