# Generated by Django 3.2.6 on 2021-09-01 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carmanagment', '0004_auto_20210901_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensestypes',
            name='type_class',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Затраты на автомобиль'), (2, 'Капитальные затраты на автомобиль'), (100, 'Прочее')], default=100, verbose_name='Класс затрат'),
        ),
    ]
