# Generated by Django 3.2.6 on 2021-09-03 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carmanagment', '0005_expensestypes_type_class'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': 'Авто', 'verbose_name_plural': 'Авто'},
        ),
        migrations.AlterModelOptions(
            name='carbrand',
            options={'verbose_name': 'Бренд', 'verbose_name_plural': 'Бренды'},
        ),
        migrations.AlterModelOptions(
            name='carmodel',
            options={'verbose_name': 'Модель', 'verbose_name_plural': 'Модели'},
        ),
        migrations.AlterModelOptions(
            name='counterpart',
            options={'verbose_name': 'Контрагент', 'verbose_name_plural': 'Контрагенты'},
        ),
        migrations.AlterModelOptions(
            name='driver',
            options={'verbose_name': 'Водитель', 'verbose_name_plural': 'Водители'},
        ),
        migrations.AlterModelOptions(
            name='expenses',
            options={'verbose_name': 'Затрата', 'verbose_name_plural': 'Затраты'},
        ),
        migrations.AlterModelOptions(
            name='expensestypes',
            options={'verbose_name': 'Тип затрат', 'verbose_name_plural': 'Типы затрат'},
        ),
        migrations.AlterModelOptions(
            name='investmentcarbalance',
            options={'verbose_name': 'Инвестор', 'verbose_name_plural': 'Инвесторы'},
        ),
        migrations.AlterModelOptions(
            name='investor',
            options={'verbose_name': 'Инвестор', 'verbose_name_plural': 'Инвесторы'},
        ),
        migrations.AddField(
            model_name='car',
            name='additional_miilage',
            field=models.PositiveIntegerField(default=0, verbose_name='Дополнительный километраж на поездку'),
        ),
        migrations.AddField(
            model_name='car',
            name='fuel_consumption',
            field=models.FloatField(default=14, verbose_name='Расход топлива'),
        ),
    ]
