# Generated by Django 3.2.6 on 2021-09-15 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carmanagment', '0009_carsinoperator_mylist_model_taxioperator'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='taxitrip',
            unique_together={('car', 'timestamp')},
        ),
    ]
