# Generated by Django 3.2.6 on 2021-09-15 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carmanagment', '0010_alter_taxitrip_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='carsinoperator',
            name='driver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='driver_in_taxi', to='carmanagment.driver', verbose_name='Машина'),
            preserve_default=False,
        ),
    ]
