# Generated by Django 3.2.6 on 2021-09-20 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carmanagment', '0011_carsinoperator_driver'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carsinoperator',
            options={'verbose_name': 'Машины в таксопарках', 'verbose_name_plural': 'Машины в таксопарках'},
        ),
    ]
