# Generated by Django 3.2.6 on 2021-09-20 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carmanagment', '0012_alter_carsinoperator_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxitrip',
            name='amount',
            field=models.FloatField(verbose_name='Сумма оплаты'),
        ),
        migrations.AlterField(
            model_name='taxitrip',
            name='car_amount',
            field=models.FloatField(verbose_name='Сумма прибыли по машине'),
        ),
        migrations.AlterField(
            model_name='taxitrip',
            name='mileage',
            field=models.FloatField(verbose_name='Пробег по трекеру'),
        ),
    ]
