# Generated by Django 3.2.6 on 2021-09-21 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carmanagment', '0014_alter_expenses_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxitrip',
            name='fuel',
            field=models.FloatField(verbose_name='Затраты на топливо'),
        ),
        migrations.AlterField(
            model_name='taxitrip',
            name='timestamp',
            field=models.DateTimeField(auto_created=True, verbose_name='Дата начала поездки'),
        ),
    ]
