# Generated by Django 3.2.6 on 2021-10-08 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carmanagment', '0015_auto_20210921_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxitrip',
            name='driver_amount',
            field=models.FloatField(default=0, verbose_name='Зарплата водителя'),
        ),
        migrations.AddField(
            model_name='taxitrip',
            name='payer_amount',
            field=models.FloatField(default=0, verbose_name='Прибыль сервиса'),
        ),
    ]
