# Generated by Django 3.2.6 on 2021-10-17 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carmanagment', '0017_tripstatistics'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripstatistics',
            name='trip_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Кол-во поездок'),
        ),
        migrations.AlterField(
            model_name='tripstatistics',
            name='amount',
            field=models.FloatField(default=0, verbose_name='Сумма оплаты'),
        ),
        migrations.AlterField(
            model_name='tripstatistics',
            name='car_amount',
            field=models.FloatField(default=0, verbose_name='Сумма прибыли по машине'),
        ),
        migrations.AlterField(
            model_name='tripstatistics',
            name='fuel',
            field=models.FloatField(default=0, verbose_name='Затраты на топливо'),
        ),
        migrations.AlterField(
            model_name='tripstatistics',
            name='mileage',
            field=models.FloatField(default=0, verbose_name='Пробег по трекеру'),
        ),
    ]
