# Generated by Django 3.2.6 on 2021-11-17 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('balance', '0004_auto_20210920_1546'),
        ('carmanagment', '0019_auto_20211018_1613'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userprofile',
            unique_together={('user', 'account')},
        ),
        migrations.CreateModel(
            name='CarInsurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_created=True, verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата завершения')),
                ('car_amount', models.FloatField(default=0, verbose_name='Страховой взнос')),
                ('franchise', models.PositiveIntegerField(default=0, verbose_name='Франшиза')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carmanagment.car', verbose_name='Машина')),
                ('insurer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carmanagment.counterpart', verbose_name='Страховщик')),
            ],
        ),
    ]
