# Generated by Django 3.2.6 on 2021-11-18 13:49

import audit_log.models.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carmanagment', '0020_auto_20211117_1159'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carinsurance',
            options={'ordering': ['-start_date', '-end_date', 'insurer__name', 'car__name'], 'verbose_name': 'Страховка', 'verbose_name_plural': 'Страховки'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Профиль пользователя', 'verbose_name_plural': 'Провили пользователя'},
        ),
        migrations.AddField(
            model_name='carinsurance',
            name='created_by',
            field=audit_log.models.fields.CreatingUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_insurance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='carinsurance',
            name='is_capital_expense',
            field=models.BooleanField(default=0, verbose_name='Покрытие капитальных затрат'),
        ),
        migrations.AddField(
            model_name='expenses',
            name='created_by',
            field=audit_log.models.fields.CreatingUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taxitrip',
            name='created_by',
            field=audit_log.models.fields.CreatingUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_taxi_trips', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='expensestypes',
            name='type_class',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Затраты на автомобиль'), (2, 'Капитальные затраты на автомобиль'), (3, 'Страховые случаи'), (100, 'Прочее')], default=100, verbose_name='Класс затрат'),
        ),
    ]
