# Generated by Django 3.2.6 on 2021-12-02 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carmanagment', '0021_auto_20211118_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='operating_costs_percent',
            field=models.FloatField(default=5.0, verbose_name='Процент на операционные затраты'),
        ),
        migrations.AddField(
            model_name='tripstatistics',
            name='lost_amount',
            field=models.FloatField(default=0, verbose_name='Не полученная прибыль'),
        ),
        migrations.AddField(
            model_name='tripstatistics',
            name='rent_amount',
            field=models.FloatField(default=0, verbose_name='Прибыль от аренды'),
        ),
        migrations.AddField(
            model_name='tripstatistics',
            name='rent_mileage',
            field=models.FloatField(default=0, verbose_name='Пробег в аренде'),
        ),
        migrations.AlterField(
            model_name='tripstatistics',
            name='mileage',
            field=models.FloatField(default=0, verbose_name='Пробег за поездки'),
        ),
        migrations.CreateModel(
            name='DriversSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carmanagment.car', verbose_name='Машина')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carmanagment.driver', verbose_name='Водитель')),
            ],
            options={
                'verbose_name': 'Расписание работы на авто',
                'verbose_name_plural': 'Расписания работы на авто',
            },
        ),
        migrations.CreateModel(
            name='CarSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fix_rent', models.BooleanField(default=True, verbose_name='Машина в аренде')),
                ('rent_price', models.FloatField(default=0.0, verbose_name='Ставка оренды')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carmanagment.car', verbose_name='Машина')),
            ],
            options={
                'verbose_name': 'Расписание работы на авто',
                'verbose_name_plural': 'Расписания работы на авто',
            },
        ),
        migrations.CreateModel(
            name='CarDayRent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата аренды')),
                ('rent_amount', models.FloatField(default=0.0, verbose_name='Ставка оренды')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carmanagment.car', verbose_name='Машина')),
            ],
            options={
                'verbose_name': 'Аренда авто',
                'verbose_name_plural': 'Даты аренды авто',
            },
        ),
    ]
