# Generated by Django 3.2.6 on 2021-12-02 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0006_cashbox'),
        ('carmanagment', '0022_auto_20211202_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxioperator',
            name='cash_box',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='balance.cashbox'),
        ),
    ]
