# Generated by Django 3.2.6 on 2021-12-05 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0006_cashbox'),
        ('carmanagment', '0024_auto_20211205_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxitrip',
            name='is_rent',
            field=models.BooleanField(default=False, verbose_name='Упущенная прибыль'),
        ),
        migrations.AlterField(
            model_name='taxitrip',
            name='transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='balance.transaction'),
        ),
    ]
