# Generated by Django 3.2.6 on 2021-12-08 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carmanagment', '0026_auto_20211205_2019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carschedule',
            name='fix_rent',
        ),
        migrations.AddField(
            model_name='carschedule',
            name='end_rent',
            field=models.BooleanField(default=True, verbose_name='Аренда завершена досрочно'),
        ),
        migrations.AddField(
            model_name='carschedule',
            name='my_break_rent',
            field=models.BooleanField(default=True, verbose_name='Разрешен досочный возврат'),
        ),
        migrations.AddField(
            model_name='carschedule',
            name='plan_rent',
            field=models.BooleanField(default=True, verbose_name='Запланированная аренда'),
        ),
    ]
