# Generated by Django 3.2.6 on 2021-12-11 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carmanagment', '0027_auto_20211208_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carschedule',
            name='deposit',
            field=models.FloatField(default=0.0, verbose_name='Залог'),
        ),
        migrations.AlterField(
            model_name='carschedule',
            name='end_rent',
            field=models.BooleanField(default=False, verbose_name='Аренда завершена досрочно'),
        ),
        migrations.AlterField(
            model_name='carschedule',
            name='plan_rent',
            field=models.BooleanField(default=False, verbose_name='Запланированная аренда'),
        ),
        migrations.AlterField(
            model_name='carschedule',
            name='rent_amount',
            field=models.FloatField(default=0.0, verbose_name='Сумма оренды'),
        ),
    ]
