# Generated by Django 3.2.6 on 2021-12-12 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carmanagment', '0028_auto_20211211_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxitrip',
            name='cash',
        ),
        migrations.AddField(
            model_name='taxitrip',
            name='many_in_cash',
            field=models.FloatField(default=0, verbose_name='Оплата наличными'),
        ),
    ]
