# Generated by Django 3.2.6 on 2021-12-20 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carmanagment', '0031_auto_20211215_2032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carschedule',
            old_name='deposit',
            new_name='paid_deposit',
        ),
        migrations.RemoveField(
            model_name='carschedule',
            name='my_break_rent',
        ),
        migrations.RemoveField(
            model_name='carschedule',
            name='plan_rent',
        ),
        migrations.RemoveField(
            model_name='carschedule',
            name='rent_amount',
        ),
        migrations.AlterField(
            model_name='carschedule',
            name='end_rent',
            field=models.DateTimeField(default=False, verbose_name='Аренда завершена'),
        ),
        migrations.CreateModel(
            name='RentPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название тарифа')),
                ('type_class', models.PositiveSmallIntegerField(choices=[(1, 'Учет в часах'), (2, 'Учет в днях')], default=2, verbose_name='Тип учета')),
                ('price', models.FloatField(default=600, verbose_name='Цена оренды в единицу времени')),
                ('min_time', models.PositiveIntegerField(default=3, verbose_name='Минимальный срок аренды')),
                ('safe_time', models.PositiveIntegerField(default=7, verbose_name='Срок аренды для расчета стоимости залога')),
                ('can_break_rent', models.BooleanField(default=True, verbose_name='Разрешен досочный возврат')),
                ('replaced_by_new', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carmanagment.rentprice')),
            ],
        ),
        migrations.AddField(
            model_name='carschedule',
            name='price',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='carmanagment.rentprice', verbose_name='тариф'),
            preserve_default=False,
        ),
    ]
