# Generated by Django 3.2.6 on 2021-12-27 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carmanagment', '0032_auto_20211220_2120'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rentprice',
            options={'verbose_name': 'Тариф аренды', 'verbose_name_plural': 'Тарифы аренды'},
        ),
        migrations.AddField(
            model_name='car',
            name='rent_price_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rent_price_cars', to='carmanagment.rentprice'),
        ),
        migrations.AlterField(
            model_name='carschedule',
            name='price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_price', to='carmanagment.rentprice', verbose_name='тариф'),
        ),
    ]
