# Generated by Django 3.2.6 on 2022-01-01 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carmanagment', '0033_auto_20211227_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='carschedule',
            name='deposit',
            field=models.FloatField(default=0.0, verbose_name='Залог'),
        ),
        migrations.AlterField(
            model_name='carschedule',
            name='end_rent',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Аренда завершена'),
        ),
        migrations.AlterField(
            model_name='carschedule',
            name='paid_deposit',
            field=models.FloatField(default=0.0, verbose_name='Оплаченый залог'),
        ),
    ]
