# Generated by Django 3.2.6 on 2022-01-04 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carmanagment', '0034_auto_20220101_1305'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentPageModelAdmin',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('carmanagment.carschedule',),
        ),
        migrations.AddField(
            model_name='carschedule',
            name='amount',
            field=models.FloatField(default=0.0, verbose_name='Оплата'),
        ),
    ]
