# Generated by Django 3.2.6 on 2022-01-06 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carmanagment', '0035_auto_20220104_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='signal',
            field=models.CharField(default='', max_length=6, verbose_name='Позывной'),
        ),
        migrations.AddField(
            model_name='carsinoperator',
            name='signal',
            field=models.CharField(default='', max_length=7, verbose_name='Позывной'),
        ),
        migrations.AlterField(
            model_name='carschedule',
            name='amount',
            field=models.FloatField(default=0.0, verbose_name='Оплаченый залог'),
        ),
    ]
