# Generated by Django 3.2.6 on 2022-01-08 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carmanagment', '0036_auto_20220106_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carschedule',
            name='car',
        ),
        migrations.RemoveField(
            model_name='carschedule',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='carschedule',
            name='price',
        ),
        migrations.DeleteModel(
            name='RentPageModelAdmin',
        ),
        migrations.AlterField(
            model_name='driversschedule',
            name='end_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.DeleteModel(
            name='CarSchedule',
        ),
    ]
