# Generated by Django 3.2.6 on 2022-01-11 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carmanagment', '0038_driver_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='profit',
            field=models.FloatField(default=50, verbose_name='Коифициент распределения прибыли'),
        ),
        migrations.AlterField(
            model_name='investor',
            name='profit',
            field=models.FloatField(default=50, verbose_name='Коифициент распределения прибыли'),
        ),
    ]
