# Generated by Django 3.2.6 on 2022-01-15 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carmanagment', '0039_auto_20220111_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='wialontrip',
            name='avg_speed',
            field=models.PositiveIntegerField(default=0, verbose_name='Средняя скорость'),
        ),
        migrations.AddField(
            model_name='wialontrip',
            name='max_speed',
            field=models.PositiveIntegerField(default=0, verbose_name='Максимальная скорость'),
        ),
        migrations.AlterField(
            model_name='wialontrip',
            name='mileage',
            field=models.FloatField(verbose_name='Пробег по трекеру'),
        ),
        migrations.CreateModel(
            name='WialonDayStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_date', models.DateField(auto_created=True, auto_now_add=True, verbose_name='Дата')),
                ('stat_interval', models.PositiveIntegerField(default=0, verbose_name='Интервал')),
                ('mileage', models.FloatField(verbose_name='Пробег по трекеру')),
                ('stop_count', models.PositiveIntegerField(default=0, verbose_name='Остановок')),
                ('park_count', models.PositiveIntegerField(default=0, verbose_name='Парковок')),
                ('drive_time', models.PositiveIntegerField(default=0, verbose_name='Время поездки')),
                ('park_time', models.PositiveIntegerField(default=0, verbose_name='Время стоянки')),
                ('avg_speed', models.PositiveIntegerField(default=0, verbose_name='Средняя скорость')),
                ('max_speed', models.PositiveIntegerField(default=0, verbose_name='Максимальная скорость')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carmanagment.car')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carmanagment.driver', verbose_name='Водитель, если известно')),
            ],
        ),
        migrations.CreateModel(
            name='CarStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_date', models.DateField(auto_created=True, verbose_name='Дата')),
                ('stat_period', models.PositiveIntegerField(default=1, verbose_name='Отчетный период')),
                ('mileage', models.FloatField(default=0, verbose_name='Пробег за поездки')),
                ('trip_count', models.PositiveIntegerField(default=0, verbose_name='Кол-во поездок')),
                ('control_mileage', models.FloatField(default=0, verbose_name='Контрольный пробег за поездки')),
                ('control_trip_count', models.PositiveIntegerField(default=0, verbose_name='Конроль поездок')),
                ('total_trip_amount', models.FloatField(default=0, verbose_name='Сумарный доход машины')),
                ('total_rent_amount', models.FloatField(default=0, verbose_name='Доход от аренды')),
                ('total_expense', models.FloatField(default=0, verbose_name='Затраты')),
                ('total_amount', models.FloatField(default=0, verbose_name='Прибыль инвестора')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carmanagment.car')),
            ],
        ),
    ]
