# Generated by Django 3.2.6 on 2022-01-15 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carmanagment', '0041_auto_20220115_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wialondaystat',
            name='stat_date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='wialontrip',
            name='start',
            field=models.DateTimeField(verbose_name='Дата начала поездки'),
        ),
    ]
