# Generated by Django 3.2.6 on 2022-01-16 16:42

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('carmanagment', '0042_auto_20220115_2324'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandingAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_date', models.DateField(default=datetime.datetime(2022, 1, 16, 16, 41, 59, 528892, tzinfo=utc), verbose_name='Дата')),
                ('amount', models.FloatField(default=0, verbose_name='Доход от брендирования')),
                ('operate', models.FloatField(default=14, verbose_name='Операционные затраты')),
                ('investor_amount', models.FloatField(default=14, verbose_name='Прибыль инвестора')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carmanagment.car')),
            ],
            options={
                'verbose_name': 'Брендирование',
                'verbose_name_plural': 'Брендирование',
                'unique_together': {('car', 'stat_date')},
            },
        ),
        migrations.CreateModel(
            name='CarSummaryStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_date', models.DateField(default=datetime.datetime(2022, 1, 16, 16, 41, 59, 518931, tzinfo=utc), verbose_name='Дата')),
                ('stat_interval', models.PositiveIntegerField(default=86400, verbose_name='Интервал')),
                ('gps_mileage', models.FloatField(default=0, verbose_name='Пробег по трекеру')),
                ('taxi_mileage', models.FloatField(default=0, verbose_name='Пробег по оператору такси')),
                ('taxi_trip_count', models.PositiveIntegerField(default=0, verbose_name='Кол-во поездок в такси')),
                ('branding_amount', models.FloatField(default=14, verbose_name='Доход за брендирование')),
                ('taxi_amount', models.FloatField(default=14, verbose_name='Доход от таксопарка')),
                ('rent_amount', models.FloatField(default=14, verbose_name='Доход от аренды')),
                ('expense', models.FloatField(default=14, verbose_name='Расходы')),
                ('operate', models.FloatField(default=14, verbose_name='Операционные затраты')),
                ('investor_amount', models.FloatField(default=14, verbose_name='Прибыль инвестора')),
                ('driver_amount', models.FloatField(default=14, verbose_name='Зарплата водителя')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='carmanagment.car')),
            ],
            options={
                'verbose_name': 'Статистика по Авто',
                'verbose_name_plural': 'Статистика по Авто',
            },
        ),
        migrations.AlterModelOptions(
            name='tripstatistics',
            options={'verbose_name': 'Суточные данные по поездкам в такси'},
        ),
        migrations.RenameField(
            model_name='tripstatistics',
            old_name='total_bank_rent',
            new_name='bank_amount',
        ),
        migrations.RemoveField(
            model_name='taxitrip',
            name='car_amount',
        ),
        migrations.RemoveField(
            model_name='taxitrip',
            name='total_payer_amount',
        ),
        migrations.RemoveField(
            model_name='tripstatistics',
            name='car_amount',
        ),
        migrations.RemoveField(
            model_name='tripstatistics',
            name='expanse_amount',
        ),
        migrations.RemoveField(
            model_name='tripstatistics',
            name='total_firm_rent',
        ),
        migrations.RemoveField(
            model_name='tripstatistics',
            name='total_payer_amount',
        ),
        migrations.AddField(
            model_name='carmileage',
            name='stat_date',
            field=models.DateField(default=datetime.datetime(2022, 1, 16, 16, 41, 59, 518931, tzinfo=utc), verbose_name='Дата'),
        ),
        migrations.AddField(
            model_name='tripstatistics',
            name='investor_amount',
            field=models.FloatField(default=0, verbose_name='Прибыль инвестора'),
        ),
        migrations.AddField(
            model_name='tripstatistics',
            name='operating_services',
            field=models.FloatField(default=0, verbose_name='Операционные затраты'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='fuel_compensation',
            field=models.FloatField(default=100, verbose_name='Процент компенсации топлива'),
        ),
        migrations.AlterField(
            model_name='tripstatistics',
            name='stat_date',
            field=models.DateField(default=datetime.datetime(2022, 1, 16, 16, 41, 59, 528892, tzinfo=utc), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='wialondaystat',
            name='stat_date',
            field=models.DateField(default=datetime.datetime(2022, 1, 16, 16, 41, 59, 530880, tzinfo=utc), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='wialontrip',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 16, 16, 41, 59, 529885, tzinfo=utc), verbose_name='Дата начала поездки'),
        ),
        migrations.DeleteModel(
            name='CarStatistics',
        ),
    ]
