# Generated by Django 3.2.6 on 2022-01-20 18:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('carmanagment', '0044_auto_20220116_2121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='additional_miilage',
            new_name='additional_millage',
        ),
        migrations.AddField(
            model_name='carsummarystatistics',
            name='capital_expense',
            field=models.FloatField(default=0, verbose_name='Капитальные расходы'),
        ),
        migrations.AddField(
            model_name='carsummarystatistics',
            name='plan_for_paid',
            field=models.BooleanField(default=False, verbose_name='Отчет требует оплаты'),
        ),
        migrations.AddField(
            model_name='carsummarystatistics',
            name='report_paid',
            field=models.DateField(blank=True, null=True, verbose_name='Дата оплаты по отчету'),
        ),
        migrations.AddField(
            model_name='expenses',
            name='franchise',
            field=models.FloatField(default=0, verbose_name='Франшиза'),
        ),
        migrations.AlterField(
            model_name='brandingamount',
            name='stat_date',
            field=models.DateField(default=datetime.datetime(2022, 1, 20, 18, 47, 29, 625863, tzinfo=utc), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='car',
            name='control_mileage',
            field=models.PositiveIntegerField(verbose_name='Контрольное значение пробега'),
        ),
        migrations.AlterField(
            model_name='carmileage',
            name='stat_date',
            field=models.DateField(default=datetime.datetime(2022, 1, 20, 18, 47, 29, 596887, tzinfo=utc), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='carsummarystatistics',
            name='stat_date',
            field=models.DateField(default=datetime.datetime(2022, 1, 20, 18, 47, 29, 596887, tzinfo=utc), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='amount',
            field=models.FloatField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='taxioperator',
            name='bank_interest',
            field=models.FloatField(default=2.5, verbose_name='Комисия за перевод (без нал)'),
        ),
        migrations.AlterField(
            model_name='taxioperator',
            name='cash_profit',
            field=models.FloatField(default=17, verbose_name='Коифициент прибили с поезди оператора (нал)'),
        ),
        migrations.AlterField(
            model_name='taxioperator',
            name='profit',
            field=models.FloatField(default=17, verbose_name='Коифициент прибили с поезди оператора (без нал)'),
        ),
        migrations.AlterField(
            model_name='tripstatistics',
            name='stat_date',
            field=models.DateField(default=datetime.datetime(2022, 1, 20, 18, 47, 29, 624867, tzinfo=utc), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='wialondaystat',
            name='stat_date',
            field=models.DateField(default=datetime.datetime(2022, 1, 20, 18, 47, 29, 627856, tzinfo=utc), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='wialontrip',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 20, 18, 47, 29, 626859, tzinfo=utc), verbose_name='Дата начала поездки'),
        ),
        migrations.AlterUniqueTogether(
            name='carsummarystatistics',
            unique_together={('car', 'stat_date', 'stat_interval')},
        ),
    ]
