# Generated by Django 3.2.6 on 2022-01-30 17:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripstatistics',
            name='stat_date',
            field=models.DateField(default=datetime.datetime(2022, 1, 30, 17, 44, 0, 500814, tzinfo=utc), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='wialondaystat',
            name='stat_date',
            field=models.DateField(default=datetime.datetime(2022, 1, 30, 17, 44, 0, 456759, tzinfo=utc), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='wialontrip',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 30, 17, 44, 0, 456759, tzinfo=utc), verbose_name='Дата начала поездки'),
        ),
    ]
