# Generated by Django 3.2.6 on 2022-02-02 17:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_auto_20220131_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripstatistics',
            name='stat_date',
            field=models.DateField(default=datetime.datetime(2022, 2, 2, 17, 56, 2, 87638, tzinfo=utc), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='wialondaystat',
            name='stat_date',
            field=models.DateField(default=datetime.datetime(2022, 2, 2, 17, 56, 2, 33197, tzinfo=utc), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='wialontrip',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 2, 17, 56, 2, 33197, tzinfo=utc), verbose_name='Дата начала поездки'),
        ),
    ]
