# Generated by Django 3.2.6 on 2022-02-08 19:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_auto_20220206_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripstatistics',
            name='stat_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='wialondaystat',
            name='stat_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='wialontrip',
            name='start',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата начала поездки'),
        ),
    ]
