# Generated by Django 3.2.6 on 2022-02-18 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_auto_20220208_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripstatistics',
            name='operator_stat',
            field=models.BooleanField(default=False, verbose_name='Статистика от оператора'),
        ),
    ]
